Repository bbip-swand/BBIP_iOS, pull requests merged in 2024-09, with the labels that each got.

#14 [Feat] SIS
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/App/BBIPApp.swift
  BBIP/BBIP/Component/CustomTextEditor.swift
  BBIP/BBIP/Component/GridButtonView.swift
  BBIP/BBIP/Component/UIVCRepresentable/ImagePicker.swift
  BBIP/BBIP/Component/ViewModifier/HideKeyboard.swift
  BBIP/BBIP/Feature/CreateStudy/CreateStudyViewModel.swift
  BBIP/BBIP/Feature/CreateStudy/SISInnerView/SISCategoryView.swift
  BBIP/BBIP/Feature/CreateStudy/SISInnerView/SISDescriptionView.swift
  BBIP/BBIP/Feature/CreateStudy/SISInnerView/SISPeriodView.swift
  BBIP/BBIP/Feature/CreateStudy/SISInnerView/SISProfileView.swift
  BBIP/BBIP/Feature/CreateStudy/SISInnerView/SISWeeklyContentView.swift
  BBIP/BBIP/Feature/CreateStudy/StudyInfoSetupView.swift
  BBIP/BBIP/Feature/UserInfoSetup/UISInnerView/UISInterestView.swift
  BBIP/BBIP/Feature/UserInfoSetup/UISInnerView/UISProfileView.swift
  BBIP/BBIP/Info.plist
  BBIP/BBIP/Resource/Assets.xcassets/Common/check.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/check.imageset/shape=check_icon.svg
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/stepper_minus.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/stepper_minus.imageset/stepper_minus.svg
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/stepper_plus.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/stepper_plus.imageset/stepper_plus.svg
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/study_profile_default.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/study_profile_default.imageset/study_profile_default.svg
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/study_profile_edit.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/study_profile_edit.imageset/study_profile_edit.svg
Labels: design, refactor, feature

#15 [UI] ApplyAsset
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/Component/GridButtonView.swift
  BBIP/BBIP/Component/ViewModifier/BBIPShadowStyle.swift
  BBIP/BBIP/Core/Constant/GridButtonContent.swift
  BBIP/BBIP/Feature/CreateStudy/SISInnerView/SISPeriodView.swift
  BBIP/BBIP/Feature/MainHome/MainHomeView.swift
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_design.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_design.imageset/category_design.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_design.imageset/category_design_dark.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_development.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_development.imageset/category_development.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_development.imageset/category_development_dark.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_etc.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_etc.imageset/category_etc.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_etc.imageset/category_etc_dark.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_hobby.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_hobby.imageset/category_hobby.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_hobby.imageset/category_hobby_dark.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_interview.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_interview.imageset/category_interview.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_interview.imageset/category_interview_dark.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_language.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_language.imageset/category_language.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_language.imageset/category_language_dark.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_license.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_license.imageset/category_license.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_license.imageset/category_license_dark.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_major.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_major.imageset/category_major.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_major.imageset/category_major_dark.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_self-improvement.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_self-improvement.imageset/category_self-improvement.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Category/category_self-improvement.imageset/category_self-improvement_dark.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Job/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Job/job_academic.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Job/job_academic.imageset/job_academic.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Job/job_etc.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Job/job_etc.imageset/job_etc.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Job/job_jobSeeker.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Job/job_jobSeeker.imageset/job_jobSeeker.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/Job/job_worker.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/Job/job_worker.imageset/job_worker.svg
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/stepper_minus.imageset/Group 632695.svg
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/stepper_minus.imageset/stepper_minus.svg
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/stepper_plus.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/stepper_plus.imageset/Group 632696.svg
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/stepper_plus.imageset/stepper_plus.svg
Labels: design, refactor

#16 [Feat] AWSS3
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: feature

#18 [Network] SignIn
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/App/BBIPApp.swift
  BBIP/BBIP/Core/Util/UserDefaultManager.swift
  BBIP/BBIP/Data/DTO/Login/LoginDTO.swift
  BBIP/BBIP/Data/DTO/Login/LoginResponseDTO.swift
  BBIP/BBIP/Data/DTO/User/SignUpDTO.swift
  BBIP/BBIP/Data/DTO/User/UserInfoDTO.swift
  BBIP/BBIP/Data/DataSource/API/UserAPI.swift
  BBIP/BBIP/Data/DataSource/AuthDataSource.swift
  BBIP/BBIP/Data/DataSource/UserDataSource.swift
  BBIP/BBIP/Data/Repository/UserRepository.swift
  BBIP/BBIP/Domain/Entity/SignUpVO.swift
  BBIP/BBIP/Domain/UseCase/User/SignUpUseCase.swift
  BBIP/BBIP/Feature/Login/LoginView.swift
  BBIP/BBIP/Feature/Login/LoginViewModel.swift
Labels: feature, Network

#19 [Network] UIS
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/App/AppState.swift
  BBIP/BBIP/App/RootView.swift
  BBIP/BBIP/Core/Service/AWSS3Manager.swift
  BBIP/BBIP/Data/DTO/User/SignUpDTO.swift
  BBIP/BBIP/Data/DataSource/API/AWSS3API.swift
  BBIP/BBIP/Data/DataSource/API/AccessTokenPlugin.swift
  BBIP/BBIP/Data/DataSource/API/UserAPI.swift
  BBIP/BBIP/Data/DataSource/UserDataSource.swift
  BBIP/BBIP/Data/Mapper/UserInfoMapper.swift
  BBIP/BBIP/Data/Repository/UserRepository.swift
  BBIP/BBIP/Domain/Entity/SignUpVO.swift
  BBIP/BBIP/Domain/UseCase/User/CreateUserInfoUseCase.swift
  BBIP/BBIP/Feature/Login/LoginView.swift
  BBIP/BBIP/Feature/UserInfoSetup/UISInnerView/UISActiveAreaView.swift
  BBIP/BBIP/Feature/UserInfoSetup/UserInfoSetupView.swift
  BBIP/BBIP/Feature/UserInfoSetup/UserInfoSetupViewModel.swift
Labels: feature, Network

#21 [Feat] MainComponent
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/Component/HeaderComponent.swift
  BBIP/BBIP/Feature/MainHome/MainHomeHeader.swift
  BBIP/BBIP/Feature/MainHome/MainHomeView.swift
  BBIP/BBIP/Feature/MainHome/NavigationBar.swift
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/calendar_active.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/calendar_active.imageset/calendar_active.svg
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/calendar_nonactive.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/calendar_nonactive.imageset/Vector.svg
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/home_active.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/home_active.imageset/icon (2).svg
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/home_nonactive.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/home_nonactive.imageset/icon.svg
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/setting_icon.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/setting_icon.imageset/setting_icon.svg
Labels: design, feature

#22 [Feat] MainHome
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/Component/CapsuleView.swift
  BBIP/BBIP/Component/MainStudyCell.swift
  BBIP/BBIP/Component/ViewModifier/BBIPShadowStyle.swift
  BBIP/BBIP/Core/Constant/StudyCategory.swift
  BBIP/BBIP/Core/Util/DateFormat.swift
  BBIP/BBIP/Domain/Entity/CommingScheduleVO.swift
  BBIP/BBIP/Domain/Entity/CurrentWeekStudyInfoVO.swift
  BBIP/BBIP/Domain/Entity/HomeBulletnboardPostVO.swift
  BBIP/BBIP/Domain/Entity/ImpendingStudyVO.swift
  BBIP/BBIP/Feature/MainHome/BBIPGuideButton.swift
  BBIP/BBIP/Feature/MainHome/BBIPTimeRingView.swift
  BBIP/BBIP/Feature/MainHome/CommingScheduleCardView.swift
  BBIP/BBIP/Feature/MainHome/CurrentWeekStudyInfoCardView.swift
  BBIP/BBIP/Feature/MainHome/Frame/BBIPHearderView.swift
  BBIP/BBIP/Feature/MainHome/Frame/BBIPTabView.swift
  BBIP/BBIP/Feature/MainHome/HomeBulletnboardCell.swift
  BBIP/BBIP/Feature/MainHome/MainHomeView.swift
  BBIP/BBIP/Feature/MainHome/MainHomeViewModel.swift
  BBIP/BBIP/Feature/MainHome/NoticeBannerView.swift
  BBIP/BBIP/Resource/Assets.xcassets/Common/bbip_guide.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/bbip_guide.imageset/bbip_guide.png
  BBIP/BBIP/Resource/Assets.xcassets/Common/detail_rightArrow.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/detail_rightArrow.imageset/detail_rightArrow.svg
  BBIP/BBIP/Resource/Assets.xcassets/Dday/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon1.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon1.imageset/dday_icon1.svg
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon2.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon2.imageset/dday_icon2.svg
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon3.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon3.imageset/dday_icon3.svg
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon4.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon4.imageset/dday_icon4.svg
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon5.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon5.imageset/dday_icon5.svg
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon6.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon6.imageset/dday_icon6.svg
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon7.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon7.imageset/dday_icon7.svg
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon8.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Dday/dday_icon8.imageset/dday_icon8.svg
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/navigation_bar.imageset/Frame 427318989.svg
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/tabbar.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/tabbar.imageset/tabView.svg
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/timeRingStick_disable.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/timeRingStick_disable.imageset/TimeRingStick.svg
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/timeRingStick_enable.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/MainHome/timeRingStick_enable.imageset/timeRingStick_enable.svg
Labels: design, feature

#23 [Feat] AttendanceCertification
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/Feature/Attendance/AttendanceCertificationView.swift
  BBIP/BBIP/Feature/Attendance/AttendanceCertificationViewModel.swift
  BBIP/BBIP/Feature/MainHome/BBIPTimeRingView.swift
  BBIP/BBIP/Feature/MainHome/MainHomeView.swift
  BBIP/BBIP/Resource/Assets.xcassets/Common/alarm.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/alarm.imageset/alarm.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/glove.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/glove.imageset/glove.svg
Labels: design, feature

#26 [Refactor] SIS
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/App/AppState.swift
  BBIP/BBIP/App/BBIPApp.swift
  BBIP/BBIP/App/RootView.swift
  BBIP/BBIP/Component/DayPickerView.swift
  BBIP/BBIP/Component/TimePickerView.swift
  BBIP/BBIP/Component/UIVCRepresentable/BBIPLottieView.swift
  BBIP/BBIP/Core/Constant/CreateStudyContent.swift
  BBIP/BBIP/Domain/Entity/StudySessionVO.swift
  BBIP/BBIP/Feature/CreateStudy/CreateStudyViewModel.swift
  BBIP/BBIP/Feature/CreateStudy/SISCompleteView.swift
  BBIP/BBIP/Feature/CreateStudy/SISInnerView/SISPeriodView.swift
  BBIP/BBIP/Feature/CreateStudy/SISInnerView/SISWeeklyContentView.swift
  BBIP/BBIP/Feature/CreateStudy/StartCreateStudyView.swift
  BBIP/BBIP/Feature/CreateStudy/StudyInfoSetupView.swift
  BBIP/BBIP/Feature/Login/LoginView.swift
  BBIP/BBIP/Feature/MainHome/MainHomeView.swift
  BBIP/BBIP/Feature/MainHome/StudySwitch/StudySwitchView.swift
  BBIP/BBIP/Feature/MainHome/UserHome/BBIPTimeRingView.swift
  BBIP/BBIP/Feature/MainHome/UserHome/UserHomeView.swift
  BBIP/BBIP/Feature/UserInfoSetup/UISCompleteView.swift
  BBIP/BBIP/Feature/UserInfoSetup/UISInnerView/UISActiveAreaView.swift
  BBIP/BBIP/Resource/Assets.xcassets/Common/add_plus.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/add_plus.imageset/Group 632734.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/common_edit.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/common_edit.imageset/common_edit.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/remove_minus.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/remove_minus.imageset/Group 6327341.svg
  BBIP/BBIP/Resource/Assets.xcassets/Common/xmark.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/xmark.imageset/xmark.svg
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/SIS_rightArrow.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/SIS_rightArrow.imageset/Vector 90.svg
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/glassess.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/glassess.imageset/glasses.svg
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/start_createStudy.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/start_createStudy.imageset/start_createStudy.svg
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/start_createStudy1.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/StudyInfoSetup/start_createStudy1.imageset/start_createStudy1.svg
  BBIP/BBIP/Resource/Assets.xcassets/UserInfoSetup/UIS_rightArrow.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/UserInfoSetup/UIS_rightArrow.imageset/rightArrow.svg
Labels: refactor

#28 [Network] SIS
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/Core/Injection/DIContainer.swift
  BBIP/BBIP/Data/DTO/Study/StudyInfoDTO.swift
  BBIP/BBIP/Data/DataSource/API/StudyAPI.swift
  BBIP/BBIP/Data/DataSource/StudyDataSource.swift
  BBIP/BBIP/Data/Mapper/StudyInfoMapper.swift
  BBIP/BBIP/Data/Repository/StudyRepository.swift
  BBIP/BBIP/Data/Repository/UserRepository.swift
  BBIP/BBIP/Domain/Entity/CreateStudy/StudyInfoVO.swift
  BBIP/BBIP/Domain/Entity/Study/StudyInfoVO.swift
  BBIP/BBIP/Domain/Entity/Study/StudySessionVO.swift
  BBIP/BBIP/Domain/UseCase/Study/CreateStudyUseCase.swift
  BBIP/BBIP/Domain/UseCase/User/CreateUserInfoUseCase.swift
  BBIP/BBIP/Domain/UseCase/User/SignUpUseCase.swift
  BBIP/BBIP/Feature/CreateStudy/CreateStudyViewModel.swift
  BBIP/BBIP/Feature/CreateStudy/SISCompleteView.swift
  BBIP/BBIP/Feature/CreateStudy/StudyInfoSetupView.swift
  BBIP/BBIP/Feature/Login/LoginView.swift
  BBIP/BBIP/Feature/UserInfoSetup/UserInfoSetupView.swift
  BBIP/BBIP/Feature/UserInfoSetup/UserInfoSetupViewModel.swift
Labels: refactor, feature, Network

#29 [Feat] UserHome_게시판
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/Component/CapsuleView.swift
  BBIP/BBIP/Core/Injection/DIContainer.swift
  BBIP/BBIP/Data/DTO/Posting/CreatePostingDTO.swift
  BBIP/BBIP/Data/DTO/Posting/PostDTO.swift
  BBIP/BBIP/Data/DataSource/API/PostingAPI.swift
  BBIP/BBIP/Data/DataSource/PostingDataSource.swift
  BBIP/BBIP/Data/Mapper/Auth/LoginResponseMapper.swift
  BBIP/BBIP/Data/Mapper/CurrentWeekPostMapper.swift
  BBIP/BBIP/Data/Mapper/Study/StudyInfoMapper.swift
  BBIP/BBIP/Data/Mapper/User/UserInfoMapper.swift
  BBIP/BBIP/Data/Repository/PostingRepository.swift
  BBIP/BBIP/Domain/Entity/Posting/PostVO.swift
  BBIP/BBIP/Domain/UseCase/Posting/GetCurrentWeekPostUseCase.swift
  BBIP/BBIP/Feature/MainHome/MainHomeView.swift
  BBIP/BBIP/Feature/MainHome/MainHomeViewModel.swift
  BBIP/BBIP/Feature/MainHome/UserHome/HomeBulletnboardCell.swift
  BBIP/BBIP/Feature/MainHome/UserHome/UserHomeView.swift
Labels: design, Network

#30 [Bug] GetCurrentWeekPost
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/Core/Extension/DateFormatter+Extension.swift
  BBIP/BBIP/Core/Extension/JSONDecoder+Extension.swift
  BBIP/BBIP/Core/Util/DateFormat.swift
  BBIP/BBIP/Data/DTO/Posting/PostDTO.swift
  BBIP/BBIP/Data/DataSource/PostingDataSource.swift
  BBIP/BBIP/Feature/MainHome/MainHomeViewModel.swift
  BBIP/BBIP/Feature/MainHome/UserHome/HomeBulletnboardCell.swift
Labels: bug

#31 [Feat] UserHome_GetCurrentWeekStudy
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/Core/Constant/StudyCategory.swift
  BBIP/BBIP/Core/Extension/DateFormatter+Extension.swift
  BBIP/BBIP/Core/Extension/JSONDecoder+Extension.swift
  BBIP/BBIP/Core/Injection/DIContainer.swift
  BBIP/BBIP/Core/Util/TimeAgo.swift
  BBIP/BBIP/Data/DTO/Study/CurrentWeekStudyInfoDTO.swift
  BBIP/BBIP/Data/DataSource/StudyDataSource.swift
  BBIP/BBIP/Data/Mapper/CurrentWeekPostMapper.swift
  BBIP/BBIP/Data/Mapper/Study/CurrentWeekStudyInfoMapper.swift
  BBIP/BBIP/Data/Mapper/Study/StudyInfoMapper.swift
  BBIP/BBIP/Data/Repository/PostingRepository.swift
  BBIP/BBIP/Data/Repository/StudyRepository.swift
  BBIP/BBIP/Domain/Entity/Posting/PostVO.swift
  BBIP/BBIP/Domain/Entity/Study/CreateStudyInfoVO.swift
  BBIP/BBIP/Domain/Entity/Study/StudyInfoVO.swift
  BBIP/BBIP/Domain/Entity/UserHome/CurrentWeekStudyInfoVO.swift
  BBIP/BBIP/Domain/UseCase/Posting/GetCurrentWeekPostUseCase.swift
  BBIP/BBIP/Domain/UseCase/Study/CreateStudyUseCase.swift
  BBIP/BBIP/Domain/UseCase/Study/GetCurrentWeekStudyInfoUseCase.swift
  BBIP/BBIP/Feature/CreateStudy/CreateStudyViewModel.swift
  BBIP/BBIP/Feature/MainHome/MainHomeView.swift
  BBIP/BBIP/Feature/MainHome/MainHomeViewModel.swift
  BBIP/BBIP/Feature/MainHome/UserHome/CurrentWeekStudyInfoCardView.swift
  BBIP/BBIP/Feature/MainHome/UserHome/HomeBulletnboardCell.swift
  BBIP/BBIP/Feature/MainHome/UserHome/UserHomeView.swift
  BBIP/BBIP/Resource/Assets.xcassets/Common/logo_placeholder.imageset/Contents.json
  BBIP/BBIP/Resource/Assets.xcassets/Common/logo_placeholder.imageset/logo_placeholder.svg
Labels: feature, Network

#32 [Feat] SwitchStudySheet
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/Component/LoadableImageView.swift
  BBIP/BBIP/Component/MainButton.swift
  BBIP/BBIP/Core/Injection/DIContainer.swift
  BBIP/BBIP/Data/DTO/Study/CreateStudyDTO.swift
  BBIP/BBIP/Data/DTO/Study/CurrentWeekStudyInfoDTO.swift
  BBIP/BBIP/Data/DTO/Study/StudyInfoDTO.swift
  BBIP/BBIP/Data/DTO/Study/StudyTime.swift
  BBIP/BBIP/Data/DataSource/API/StudyAPI.swift
  BBIP/BBIP/Data/DataSource/StudyDataSource.swift
  BBIP/BBIP/Data/Mapper/Study/CreateStudyInfoMapper.swift
  BBIP/BBIP/Data/Mapper/Study/CurrentWeekStudyInfoMapper.swift
  BBIP/BBIP/Data/Mapper/Study/StudyInfoMapper.swift
  BBIP/BBIP/Data/Repository/StudyRepository.swift
  BBIP/BBIP/Domain/Entity/Study/CurrentWeekStudyInfoVO.swift
  BBIP/BBIP/Domain/Entity/Study/StudyInfoVO.swift
  BBIP/BBIP/Domain/Entity/UserHome/HomeBulletnboardPostVO.swift
  BBIP/BBIP/Domain/UseCase/Study/GetCurrentWeekStudyInfoUseCase.swift
  BBIP/BBIP/Domain/UseCase/Study/GetOngoingStudyUseCase.swift
  BBIP/BBIP/Feature/MainHome/Frame/BBIPTabView.swift
  BBIP/BBIP/Feature/MainHome/MainHomeView.swift
  BBIP/BBIP/Feature/MainHome/MainHomeViewModel.swift
  BBIP/BBIP/Feature/MainHome/StudyHome/StudyHomeView.swift
  BBIP/BBIP/Feature/MainHome/StudySwitch/StudySwitchView.swift
  BBIP/BBIP/Feature/MainHome/UserHome/CurrentWeekStudyInfoCardView.swift
Labels: feature, Network

#33 [Feat] DeepLink
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/App/AppState.swift
  BBIP/BBIP/App/RootView.swift
  BBIP/BBIP/Component/JoinStudyCustomAlert.swift
  BBIP/BBIP/Core/Extension/View+Extension.swift
  BBIP/BBIP/Domain/Entity/DeepLinkAlertData.swift
  BBIP/BBIP/Info.plist
Labels: feature

#36 [Feat] StudyHome_Bulletn
  BBIP/BBIP.xcodeproj/project.pbxproj
  BBIP/BBIP/Core/Injection/DIContainer.swift
  BBIP/BBIP/Data/DataSource/API/PostingAPI.swift
  BBIP/BBIP/Data/DataSource/PostingDataSource.swift
  BBIP/BBIP/Data/Mapper/Study/FullStudyInfoMapper.swift
  BBIP/BBIP/Data/Repository/PostingRepository.swift
  BBIP/BBIP/Domain/UseCase/Posting/GetStudyPostingUseCase.swift
  BBIP/BBIP/Feature/MainHome/StudyHome/StudyHomeView.swift
  BBIP/BBIP/Feature/MainHome/StudyHome/StudyHomeViewModel.swift
  BBIP/BBIP/Feature/MainHome/StudyHome/WeeklyStudyContentCell.swift
  BBIP/BBIP/Feature/MainHome/UserHome/BulletnboardCell.swift
  BBIP/BBIP/Feature/MainHome/UserHome/UserHomeView.swift
Labels: feature
